### ISSUE TITLE
Write Morning Step 1 -- What is Elm?

### ISSUE THREAD

**Issue by raorao** [elmbridge/curriculum#1]
- Learning Goals: Students understand how Elm fits in to technologies they know.
  - Structure of in-person lesson: 10 minute lecture on what elm is, with questions. Don't get too far into the approach or reasons for elm -- that will be covered in a future section.
  - Structure of written lesson:
    - Section on how elm relates to JS. (Browsers don't understand elm!) reference other compiled languages to explain
    - Section on what elm is used for (dynamic web pages) and what it isn't used for (servers, databases, etc.)

**Comment by avh4** [comment]
also important: what are the benefits of using Elm:  

  - no runtime errors (think null pointer exceptions)
  - no confusing state manipulations (a single view function that operates on all data vs using jquery)
  - compiler helps you with refactorings

Note that to get those benefits requires a significantly different language, and as a result a lot of the Elm syntax is different from other languages like ruby, python, javascript

**Comment by avh4** [comment]
Rao says: "something like “this is great! but because it’s great, some things are weird""  https://elmlang.slack.com/archives/elmbridge-organizers/p1476507884000037
