### ISSUE TITLE
Is the tutorial specific to Elm 0.17.1?

### ISSUE THREAD

**Issue by z5h** [elmbridge/curriculum#120]
## Context:
https://elmbridge.github.io/curriculum/

## Problem:
The text reads
> If you see the following message, you are ready to go!
> `elm-repl 0.17.1`

The current version of Elm is 0.18.

## Possible solution or next step:
If this works for 0.18, the text should be updated. Otherwise a note giving special instructions on how to install older versions of Elm is needed.

**Comment by avh4** [comment]
Yeah, I think that text was missed when we updated the curriculum for 0.18.  (The most recent workshop was done with all students using Elm 0.18)

**Comment by michaelglass** [comment]
can we close this issue?

**Comment by michaelglass** [comment]
can we close this issue

**Comment by avh4** [comment]
Fixed during the upgrade to Elm 0.19
