### ISSUE TITLE
Upgrade to 0.19

### ISSUE THREAD

**Issue by tesk9** [elmbridge/curriculum#121]
## Context:
(Describe the situation that led you to discover the issue.)

## Problem:
(What is the pain point and who does it affect?)

## Possible solution or next step:
(If you have an idea for how to resolve the problem, please let us know! If not, no worries!)

**Comment by quelledanielle** [comment]
https://github.com/elmbridge/curriculum/pull/123

**Comment by michaelglass** [comment]
remaining stuff here: 
- [ ] https://github.com/elmbridge/elmoji-translator/pull/9
- [ ] https://github.com/elmbridge/elm-basics/pull/12
- [ ] update links in curriculum

**Comment by michaelglass** [comment]
I think we can close this! 🎉

**Comment by avh4** [comment]
Thanks!
