### ISSUE TITLE
Write Morning Step 2 -- Installation Instructions

### ISSUE THREAD

**Issue by raorao** [elmbridge/curriculum#2]
step by step instructions on loading elm to their computer. We're only going to be using elm-make and elm-repl. Look at other railsbridge guides for guidance on what this should look like.
    - Go to http://elm-lang.org → Get Started → Download installer
    - Run the installer
    - Go to terminal
    - Run `elm`  and verify Elm 0.17.1

**Comment by avh4** [comment]
(Linux users will have to use npm)

**Comment by raorao** [comment]
perhaps we should just standardize on npm?

**Comment by avh4** [comment]
I think Linux will be rare.  I think the installers are better for Mac/Win.

**Comment by raorao** [comment]
my sense is that we can roll this into #1 .

**Comment by avh4** [comment]
IRL, Installation will happen in the morning before the main workshop starts.  I guess the question is where does it fit best in the written material for people who are reading it on their own

**Comment by raorao** [comment]
oh, good call. I wonder if we should throw installation into `Getting Started`, since that's where people will likely gravitate to.
