### ISSUE TITLE
Add conditional logic/booleans to "The Basic Building Blocks of Elm"

### ISSUE THREAD

**Issue by raorao** [elmbridge/curriculum#26]
requires changes to https://github.com/elmbridge/intro-to-elm-part-1 as well. 

- assertion for a boolean (set to False, return True instead)
- assertion for if/else fork 
- assertion for if/else if/else fork
- assertion for case statement (perhaps on an empty list?)

**Comment by avh4** [comment]
Added two examples to https://github.com/elmbridge/intro-to-elm-part-1

**Comment by raorao** [comment]
punting on case statements, will be implemented as a part of https://github.com/elmbridge/curriculum/issues/27
