### ISSUE TITLE
Write Morning Step 3 -- Getting Started

### ISSUE THREAD

**Issue by raorao** [elmbridge/curriculum#3]
- Practical Goals: Students should be able to load the repl and do basic transformations.
  - Learning Goals: Students should start mapping elm to languages they know.
  - Structure of in-person lesson: Teacher should walk through the lessons alongside students, live coding in the repl.
  - Structure of written lesson:
    - How to use the repl (with explicit instructions on how to close it)
    - Section on strings (with explanation of repl output)
      - Defining literal strings
      - String concatenation with `++`
      - Calling functions, like `String.toUpper`, `String.split`
    - Section on numbers with addition as an example
    - Section basic functions (perhaps an add2 function)
      - end with defining `sayHello name = "Hello, " ++ name` (this is the same as the first example in the next part of the curriculum)

**Comment by raorao** [comment]
assigning to you @avh4 as you have ideas for the various sections in this step.

**Comment by avh4** [comment]
FYI, I don't have any more work in progress at the moment.

**Comment by raorao** [comment]
Closing this, as it is implemented on master.
