### ISSUE TITLE
Make better record examples in "Building Blocks of Elm"

### ISSUE THREAD

**Issue by avh4** [elmbridge/curriculum#32]
This will also change https://github.com/elmbridge/intro-to-elm-part-1

<img width="658" alt="screen shot 2016-10-15 at 5 20 57 pm" src="https://cloud.githubusercontent.com/assets/1222/19414268/cfb1d852-92fb-11e6-9b33-3de979fac791.png">
<img width="677" alt="screen shot 2016-10-15 at 5 21 06 pm" src="https://cloud.githubusercontent.com/assets/1222/19414269/d3916730-92fb-11e6-90fb-fc2208801887.png">
<img width="675" alt="screen shot 2016-10-15 at 5 21 17 pm" src="https://cloud.githubusercontent.com/assets/1222/19414270/d67244ba-92fb-11e6-9962-9183f4b9652d.png">

**Comment by tesk9** [comment]
https://github.com/elmbridge/intro-to-elm-part-1/pull/4 has an impact here. Not sure what you all think

**Comment by avh4** [comment]
I made a PR for this: https://github.com/elmbridge/intro-to-elm-part-1/pull/9  cc @raorao @tesk9 @ento

**Comment by avh4** [comment]
https://github.com/elmbridge/elm-basics/pull/9 was merged.
