### ISSUE TITLE
"Why Elm?" section: why not be more mainstream?

### ISSUE THREAD

**Issue by avh4** [elmbridge/curriculum#34]
> So why would developers choose to use this new tool, instead of a more mainstream tool? Indeed, Elm shares many of its opinions about architecture and code quality with the popular JS frameworks. However, elm is distinct in one important way — because it is a distinct programming language, not simply a framework, it can strictly enforce it's opinions.

In the above paragraph, I think a stronger point would be to talk about "why go to the trouble of learning a whole new language vs just using a JS framework" instead of the current "why use something new instead of something more mainstream"

**Comment by raorao** [comment]
:heart: the rephrasing.
