### ISSUE TITLE
"Why Elm?" section: no debugger?

### ISSUE THREAD

**Issue by avh4** [elmbridge/curriculum#37]
> elm's strict ruleset makes building a runtime debugger impossible

I don't think that's true.  More accurate would be something like, "there current is no interactive debugger for Elm programs (because it's still a new language)"

**Comment by raorao** [comment]
perhaps worth removing the section on runtime debugging entirely. It clouds the underlying point, anyway — there are common mutation-based tactics in OO languages that are impossible in elm, which can cause discomfort in beginners.
