### ISSUE TITLE
Write Morning Step 4 -- The Fundamentals

### ISSUE THREAD

**Issue by raorao** [elmbridge/curriculum#4]
- Starting code: TBD
  - Ending code: TBD
  - Practical Goals: Students should be able to use the assertion app.
  - Learning Goals: Students should start to get used to the cycle of changing code in their editor, seeing it compile, and then checking the browser.
  - Structure of in-person lesson: This should be mostly self guided, after a short explanation and example of how to use the assertion app. Teachers and T/As will provide support to students as they work through examples.
  - Structure of written lesson:
    - Section on how to use the app.
    - Section on Functions (repeat last Repl section)
    - Section on If/Else statements

**Comment by raorao** [comment]
assigning to you @avh4 as you have ideas for the various sections in this step. Please fill in the outline and unassign.

**Comment by avh4** [comment]
FYI, I don't have any more work in progress at the moment.

**Comment by raorao** [comment]
Much of this has been implemented. I think the section on functions is fairly well covered in `Getting Started`, so I don't think we need to recap. If/Else is issued in https://github.com/elmbridge/curriculum/issues/26
