### ISSUE TITLE
What am I supposed to do with the checkboxes?

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#46]
![image](https://cloud.githubusercontent.com/assets/21108/19420149/7af9b60a-939a-11e6-82d2-034beb60c1d5.png)

A note on their expected usage when it first appears would be nice.

**Comment by raorao** [comment]
Honestly, I'm not sure 😅 . I was just copying the first couple releases written by @avh4 . Agnostic on whether keep them around

**Comment by avh4** [comment]
The railsbridge curriculum is set up like this, so I copied the idea.  Students can optionally check the boxes to keep track of where on the page they are.  http://docs.railsbridge.org/intro-to-rails/getting_started#step2

**Comment by raorao** [comment]
closing this for now, could potentially be resolved by https://github.com/elmbridge/curriculum/issues/80
