### ISSUE TITLE
Getting Started > Step 5 starts out with an incomplete sentence

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#48]
https://github.com/elmbridge/curriculum/blob/96cb238de6fbea8aecb3ce8729b06738a9d038a6/Getting%20Started.md#-step-5

![image](https://cloud.githubusercontent.com/assets/21108/19420217/7d5501b0-939b-11e6-8b50-a7d4840dbc5a.png)

> To call a function in Elm,

**Comment by raorao** [comment]
assigning you @avh4 as this seems to come from your original draft, and I wonder if you have a version of this text cached locally. feel free to throw back.

**Comment by avh4** [comment]
Fixed in https://github.com/elmbridge/curriculum/commit/d29e3bc80509a829eeed770aea404df18e7ce5a7
