### ISSUE TITLE
The Basic Building Blocks of Elm: not clear what "this release" is referring to

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#49]
![image](https://cloud.githubusercontent.com/assets/21108/19420228/a59306ae-939b-11e6-9bf8-d6d41ec20d2e.png)

https://github.com/elmbridge/curriculum/blob/96cb238de6fbea8aecb3ce8729b06738a9d038a6/The%20Basic%20Building%20Blocks%20of%20Elm.md#the-basic-building-blocks-of-elm

"this release" also appears in "Making it Dynamic" and other pages.

**Comment by raorao** [comment]
yeah, I think I'd like the standardize on the following terminology:

- a *lesson* is an entire section of the curriculum (e.g. a markdown file). 
- a *step* is a subsection of a lesson
- a *release* is not a user-facing term, but simply how we tag the various parts of the emoji-translator app

**Comment by ento** [comment]
👍
