### ISSUE TITLE
The Basic Building Blocks of Elm: a little lost which to follow after Step 1: the steps or the intro app's goals

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#50]
It feels like the intro app and this doc goes out of sync at this point. Should I try to make them all pass now? Does the next step (Step 2) cover the first goal of the intro app?

![image](https://cloud.githubusercontent.com/assets/21108/19420304/8fd77e60-939d-11e6-894a-dc5867f3be80.png)

Maybe make a 1-to-1 correspondence between the intro app's sections and the guide's steps. The intro app can have a "Step 1: use elm-reactor" section, which is marked already complete from the start.

**Comment by raorao** [comment]
Hm, perhaps we should just make the first "goal" seem less immediate. something like:

> This application contains a series of assertions designed to teach you about the basic data structures of Elm. All the code for the application lives [...]

**Comment by ento** [comment]
👍
