### ISSUE TITLE
Function names and comments are of the same color in code blocks

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#52]
Not a big deal, but the function name looks a little unimportant.

![image](https://cloud.githubusercontent.com/assets/21108/19420385/6018dd8e-939f-11e6-8b7a-ea0bb6bd8942.png)

Seems to be coming from: https://github.com/GitbookIO/plugin-highlight/blob/adb1068edf9640e48b738aacfedfd41b476304c9/less/white.less#L3-L7

**Comment by raorao** [comment]
feel like this has to be fixed upstream. tagging as a wontfix

**Comment by avh4** [comment]
We should be able to orverride the color in `styles/website.css`

**Comment by avh4** [comment]
Fix proposed in https://github.com/elmbridge/curriculum/pull/78

**Comment by avh4** [comment]
Fixed in #78 (function names are now blue)
