### ISSUE TITLE
The Basic Building Blocks of Elm: too much scrolling to see if my code passed

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#53]
By the end of Step 3, it's getting a pain to scroll down every time I refresh. Maybe better to have each step in a separate file.

**Comment by raorao** [comment]
@avh4 has plans to make things collapsable to resolve this problem. fragment identifiers would also work. 

regardless, doesn't seem to be an issue that can be resolved in this repo, so I'm closing this issue.

**Comment by raorao** [comment]
see: https://github.com/elmbridge/intro-to-elm-part-1/issues/3
