### ISSUE TITLE
The Basic Building Blocks of Elm > Step 3: more clarity around "default functions"

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#54]
> You can learn more about the default functions of the language in the documentation for the Basics module.

I can see that it's a short-hand for "functions imported by default", but "default functions" seems to take on a different meaning (function bodies provided by default by Elm? is it some magic?). 

Also, the Basics module doesn't cover `if ` and `case` expressions. Which of the stuff mentioned in this step are readers expected to go and learn? Operators? (Might be good to mention that these are functions)

maybe:

> You can learn more about the basic operators provided by the language in the documentation for the Basics module.

**Comment by raorao** [comment]
this was resolved in https://github.com/elmbridge/curriculum/commit/72c6b66d7baeac124032c523b85ac44312f50cfb

**Comment by ento** [comment]
ah, this one is in a later lesson (Basic Building Blocks)

![image](https://cloud.githubusercontent.com/assets/21108/19425894/e2fa2e86-93ec-11e6-9acc-38977880488a.png)

**Comment by raorao** [comment]
good catch. I wonder if we even need that sentence, given that we reference the basics module elsewhere.
