### ISSUE TITLE
The Basic Building Blocks of Elm > Step 5: are dicts/hashes/JS objects the right metaphor for records?

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#55]
> Just like Ruby has hashes and JavaScript has objects, Elm has **records** to store key-value pairs. Unlike those other languages, though, Elm does not allow you to change the number of keys of a record after creation. A record with three keys always has three keys, no matter what.

It's just not the number of keys, but also the name of the keys.

"Just like Ruby and JavaScript can store attributes on objects"..?

**Comment by raorao** [comment]
I'd like to keep a reference to hashes/objects, to push students to map records onto data structures they already know. maybe the reference to number is the issue here. perhaps instead:

> [...], Elm does not allow you to alter the keys of a record after creation. You cannot add, edit, or remove the keys of a record after it has been defined.

**Comment by ento** [comment]
👍

**Comment by ento** [comment]
- "So Elm doesn't have 'mutable' dicts" (yes, in fact)
  - "Just like JavaScript has objects"?
- To me, the semantics of a "key" is different from the name of a field of an Elm record: key is an independent object you supply to a hash-like object to get its corresponding value
  - Say "name-value pairs" or "fields"?

**Comment by raorao** [comment]
The goal of this section is familiarize students with records, and perhaps the metaphor of record -> hash/object is simply too awkward. Any suggestions for alternatives, perhaps without a metaphor at all? Would love to see a proposed rewrite.

**Comment by avh4** [comment]
When I did trial runs, it made sense to the student to say "a record is like a javascript object, except you can't add or remove fields, and you can't change the type of any field"

**Comment by ento** [comment]
I'm going to try editing with the following naming scheme:

- a record has fields
- a field has a name and a value
