### ISSUE TITLE
The Basic Building Blocks of Elm > Step 5: grandmotherNames is hard to make the first move

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#57]
Since you can't see what the inputs are. Maybe add somewhere: "Hint: take a stab in the dark and see what the error message can tell you"

**Comment by avh4** [comment]
`grandmotherNames` was replaced by `kingPhilipCanOrderFineGreenSocks` (which may also be replaced by people-related questions https://github.com/elmbridge/curriculum/issues/32 )

**Comment by ento** [comment]
`kingPhilipCanOrderFineGreenSocks`: I can see all the data I need to work with - issue fixed 👍
