### ISSUE TITLE
Why Elm: "ES6 build tools" is ambiguous

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#59]
"transpilers" may not be a beginner-friendly term. Also the world may no longer have ES6 transpilers in the future.  Maybe leave it out?

**Comment by raorao** [comment]
The goal of the sentence was to compare elm to other compiled languages that the reader may be familiar with. Maybe JSX would be a better example?

**Comment by ento** [comment]
👍 and more Googleable
