### ISSUE TITLE
Why Elm: is it variables, or values that's immutable?

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#60]
> Variables, once defined, can never change.
> something to become `undefined`

seem to imply that re-assigning to a variable is prohibited. (["single assignment"](https://en.wikipedia.org/wiki/Assignment_(computer_science)#Single_assignment))

> a function to accidentally change its inputs
> you have to create a new list with all the elements you specify

these are saying that values are immutable.

I'll probably feel better if the last sentence referenced that same concept as the opening sentence:

> Variables like these are called **immutable**.

But not sure if it captures the concept of immutable objects/values.

**Comment by raorao** [comment]
I think you are totally right about the reference to `variables` making this section awkward. I'd be happy to switch to `values`, but I couldn't figure out the wording for the first sentence:

> **Values, once defined, can never change.**

That feels a little off. Any suggestion on a rewrite?

**Comment by raorao** [comment]
I think I'm going with 

> **Once a value is declared in an Elm application, it can never change**

**Comment by ento** [comment]
👍
