### ISSUE TITLE
Why Elm > Everything in Elm has a *type*: example may imply strongly typed, not statically typed

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#61]
> For instance, if you make a `length` function that takes a string and returns an integer, it is not possible for that function to return a float, another string, or a null value (in fact, there are no null values in the entire language).

A dynamically & strongly typed language may match this description, if you define those as:

- dynamic: type is checked at run-time
- strong: no implicit conversion between types like JavaScript does

and the reader may imagine that's the case (that there will be run-time errors).

maybe: in the next sentence, say that the compiler will catch those errors:

> Those same constraints are enforced by the Elm compiler on everything in the language, including variables, functions, and complex data structures.

**Comment by raorao** [comment]
I understand the issue here, but I don't want to reference compiling — the concept introduced later in the lesson. 

Instead, I rewrote this as:

> **Everything in Elm has a *type*. Nothing can ever break that contract.** For instance, it is not possible for a function to return a string in some cases and a number in other cases — the type contract of a function can never be violated. Those same constraints operate on everything in the language, including variables and complex data structures. That is why Elm is called a **statically typed** language.

let me know what you think

**Comment by ento** [comment]
Reads 👍 to me, thanks!
