### ISSUE TITLE
Choose Your Own Emoji: is "parameterized values" an established term?

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#66]
![image](https://cloud.githubusercontent.com/assets/21108/19428520/819b4914-93ff-11e6-8302-49c6a5374513.png)

I believe it's good to stick to established/canonical terms where possible so that readers can Google or apply the knowledge to other resources. If the established term is not well-named and we'd like to introduce a better name for the curriculum, I think it should be at least mentioned.

And for "parameterized values", I wasn't sure if it's an established term ..and [Google](https://www.google.com/search?q=elm+%22parameterized+value%22) isn't helpful.

- [Intro to Elm](https://guide.elm-lang.org/types/union_types.html) gets away with not naming them (or introducing the concept of constructors is a substitute)
- [Elm Friday](https://blog.codecentric.de/en/2016/03/elm-friday-part-10-union-types/) says tagged union values (in the sense of values of a tagged union)
- [elm-explained](https://github.com/niksilver/elm-explained/blob/master/types/UnionTypes.md) also says "tagged `Value` and tagged `String` types"
- [this book](https://books.google.com/books?id=rh8GC7p0JTUC&pg=PA23&lpg=PA23&dq=union+types+tagged+value&source=bl&ots=Tz2MoFvzXS&sig=hiI8BT5hXFFNF5siZT4_sS4PBuY&hl=en&sa=X&ved=0ahUKEwjJrKPypuHPAhUm24MKHTYMAVwQ6AEIVTAJ#v=onepage&q=union%20types%20tagged%20value&f=false) also says something like "*tagged value* `Left v1` carrying a *value* `v1` of type `T1`"

**Comment by raorao** [comment]
Yeah, it's a made up term. 

I have a larger rewrite brewing to this section + the union type section, so I'm happy to throw a fix in with that. **tagged value** seems fine, but perhaps I can get away without naming them at all.
