### ISSUE TITLE
Emojification: guessing the purpose and signature of exposed functions feels contrived

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#67]
![image](https://cloud.githubusercontent.com/assets/21108/19429363/2ca75484-9404-11e6-8fff-e14ecf5b04e6.png)

> We can make some guesses as to purpose and signature for these functions, based on their names.

In real life, I think I'd go see the source/comment/signature of the function I want to use. Maybe make a note: "For the sake of learning, let's try using them based on just our guesses"

**Comment by raorao** [comment]
this line got shuffled around in rewrites, and I don't think it makes any sense anymore. Happy to just kill it entirely.
