### ISSUE TITLE
Our First Full Feature: what's a type alias's behavior?

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#69]
![image](https://cloud.githubusercontent.com/assets/21108/19429617/7ea62bf6-9405-11e6-8db1-f9294077864a.png)

> The only difference [from a union type] is that type alias shares its behavior with the type to which it is aliased.

I'm not sure how to understand what behavior is shared

**Comment by raorao** [comment]
yeah, that doesn't make any sense! how about something like:

> The code above declares that `Model` is a **type alias** for a record. A type alias works a lot like a union type declaration — it also produces a new type that we can use in our program. In this case, the `Model` type is just another name for "record with key `currentText`". Type aliases are helpful for making type signatures simple and readable.

**Comment by ento** [comment]
😻 

how about:

- make it clear that a type alias is not a substitute for a record value
  - "`Model` is a **type alias** for a specific shape of a record"
- show how a type signature might be without a type alias

---

The code above declares that `Model` is a **type alias** for a specific shape of a record. A type alias works a lot like a union type declaration — it also produces a new type that we can use in our program. In this case, the `Model` type is just another name for "a record with a single key called `currentText`."

Type aliases are helpful for making type signatures simple and readable. For example, you can see that `Model` is used in the type signature for `init`:

```
init : Model
init =
    { currentText = "" }
```

Without this type alias, we would've had to write:

```
init : { currentText : String }
init =
    { currentText = "" }
```

Now back to business: we'll need to extend this type alias declaration, by adding another key to the record:
...

**Comment by raorao** [comment]
Perfect! Will implement this afternoon.

**Comment by ento** [comment]
thanks! though noting that https://github.com/elmbridge/curriculum/issues/32 might introduce type aliases earlier in the curriculum
