### ISSUE TITLE
The Elm Architecture: record can change over time? what about immutability?

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#70]
![image](https://cloud.githubusercontent.com/assets/21108/19429705/e036d8de-9405-11e6-82c1-0b62cb8f9f96.png)

> This record represents the state of our application — it is the only thing in our entire application that can change over time. As the model changes, the UI should change to reflect its new value

In Why Elm, we talked about how once a value is declared, it doesn't change, ever. I wonder what's a good way to explain how `model` can change without changing.. or if people can get confused with this line or not.

**Comment by raorao** [comment]
I've been puzzling over a rewrite, and I'm totally stuck. would appreciate some suggestions.

**Comment by ento** [comment]
suggestion:

----

Step for `init`:

But wait, didn't we say that an Elm value can never change? What's exactly changing here? Good question -- let's come back to it when we finish looking at the rest of the pieces.

...

Step for `update`:

Now back to the question of change we saved for later when we were looking at `init`: what does it mean when we say `model` changes? The key is in the first diagram..

even though we said `model`, `view`, and `update` together form a triad, you can see that `model` is not a first-class circle in this diagram. In fact, `model` is just passed around as an argument to `view` and `update` functions. The `model` argument may be different each time those functions are called -- because `update` returns a new value as the updated application state and the old value gets discarded! So you see, changing the `model` doesn't mean modifying its value, but pointing the `model` argument at a different value.

**Comment by raorao** [comment]
😍😍😍😍. This is awesome, and totally in the voice of the curriculum.
