### ISSUE TITLE
Does open work for Windows users?

### ISSUE THREAD

**Issue by siruguri** [elmbridge/curriculum#86]
In `The%20Elm%20Architecture.md`, a browser window is opened via CLI with `open`

Does this work in Windows/Cygwin, and if not, what should be the suggested method?

Maybe say "double-click index.html, or open via File->Open in your browser" as the default instruction, and have a special tip to use `open` for *nix users?

PS: trying to find the answer to "open alternative in windows" on Goognet is fruitless :)

**Comment by siruguri** [comment]
cygwin, that was the trick!

http://stackoverflow.com/questions/577595/open-a-file-from-cygwin

Is this the answer? I don't want to PR this unless someone here has Cygwin.

**Comment by raorao** [comment]
My teaching experience has pushed me away from "open in your browser" instructions, because its common for junior engineers to not understand they can open a file like that. That said, my teaching experience has been almost entirely *nix-based, so I appreciate that it might not be inclusive. 

Would appreciate a suggested rewrite!

**Comment by avh4** [comment]
I think it would be good to add how to open it from the GUI.

**Comment by siruguri** [comment]
@raorao - could you explain the observation, "junior engineers [do] not understand they can open a file like that", in terms of why that's hard to teach? I'd hope that in most combinations of OS/browser, there is either a File/Open or a drag-drop option to basically render an HTML page from disk, but I might be wrong.

I'm happy to submit a PR with this alternate set of instructions added to the `open` line... should I wait till someone assigns this issue to me, for coordination purposes?

**Comment by raorao** [comment]
>  could you explain the observation, "junior engineers [do] not understand
they can open a file like that", in terms of why that's hard to teach?

It's not hard to teach, it just often contradicts junior engineer's (false)
mental model of a distinction between code-world and OS-world. It's an
important lesson to learn, not sure we have to be the ones to teach it.

It may not even be a particularly big jump for the audience of this
curriculum. And anyways, using `open` may not be defensible if we expect
there to be a fair number of non-*nix users.

A PR would definitely be welcome! just mention this issue when you submit
it.

**Comment by raorao** [comment]
no longer necessary after #88
