### ISSUE TITLE
Say a bit more about union types

### ISSUE THREAD

**Issue by siruguri** [elmbridge/curriculum#91]
I think union types are important/interesting enough to merit a bit more of an explanation in the initial sections, even if students aren't going to use it right away.

I'll submit a PR with my proposed text edits shortly.

**Comment by raorao** [comment]
I am not convinced that we need another section explaining union types, especially as a part of a section attempting to explain the elm architecture, which is much more vital for students to learn.

If you feel that the current text raises more questions than it answers, I think there are three ways forward:

- reduce or remove the current text to hand-wave past union types entirely. 
- add more text to the union type section later in the curriculum. 
- add a bonus example in the morning explaining union types (functionally resolving https://github.com/elmbridge/curriculum/issues/27, and link backwards.

**Comment by siruguri** [comment]
I can't do it tonight but I agree that reducing the text in the
architecture section and linking to a fuller explanation elsewhere, makes
sense... I'd be happy to get around to it in the (near) future.

**Comment by brookeangel** [comment]
Closing this issue. The text surrounding union types has been slightly modified since this issue was created, and has been given the 👍. Feel free to create a new issue if you have additional suggestions!
