### ISSUE TITLE
Introduction.md says 5 hours, but our schedule adds up to 5.5 hours

### ISSUE THREAD

**Issue by ento** [elmbridge/curriculum#99]
Introduction.md:

> This tutorial is meant to be completed over the course of 5 hours, broken up into two chunks:
>  - 1.5 hours on learning the basics of the language.
>  - 3.5 hours building an Elm application from scratch — specifically, an emoji translator!

[Schedule:](https://groups.google.com/forum/#!msg/elmbridge-volunteers/PWp83fVKew8/k0d99DZQAwAJ)

> 8:30-9:30am: Check-in, breakfast, and software installation (please arrive by 9am at the latest) 
> 9:30am: Opening talk, student sorting 
> 10am: Code 
> 12:30pm: Lunch 
> 1:30pm: Code 
> 4:30pm: Closing talk, announcements & retrospectives 

2.5 hours + 3 hours = 5.5 hours

should Introduction.md say:

> This tutorial is meant to be completed over the course of 5.5 hours, broken up into two chunks:
>  - 2.5 hours on learning the basics of the language.
>  - 3 hours building an Elm application from scratch — specifically, an emoji translator!

**Comment by raorao** [comment]
good catch. will update.

**Comment by raorao** [comment]
resolved in https://github.com/elmbridge/curriculum/commit/71d62daddab38163aae6b52bbdca4605f71823ec
